#!/bin/bash

#SET COMPARTMENT
profile=DEFAULT
compartment_id=ocid1.compartment.oc1..aaaaaaaathxc5bc6bv5qgqrzpc2ggnv2lrpcgsvbjpgugoiylw64s3qi6yia

#IF USING AN EXISTING NETWORK SET
vcn_id=
subnet_id=

#SET GLUSTER SERVER
gluster_server_shape=BM.DenseIO2.52
image=Oracle-Linux-7.5-2018.10.16-0
region=us-ashburn-1 #us-phoenix-1,us-ashburn-1,eu-frankfurt-1,uk-london-1
ad=1
server_nodes=2
blksize_tb=1
blk_num=0
full_CIDR=10.0.2.0

#CALCULATED VARIABLES
PRE=`uuidgen | cut -c-5`
USER=opc
AD=`oci iam availability-domain list --profile $profile -c $compartment_id --region $region | jq -r .data[].name | grep -e '-'$ad`
OS=`oci compute image list -c $compartment_id --region $region --all | jq -r '.data[] | select(."display-name" | contains ("'$image'")).id'`
INFO='--profile '$profile' --region '$region' --availability-domain '$AD' -c '$compartment_id
subnet=`echo $full_CIDR | awk -F. '{print $1"."$2"."$3}'`

#BASH COLORS
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color
