#!/bin/bash

#SET TENANCY
USER=opc
server_nodes=3
full_CIDR=10.0.2.0
vcn_id=ocid1.vcn.oc1.phx.aaaaaaaauuihsosn6ehnjhbhgy5c45yz4r5zypnd4xexujp5ldheyaqk3o2q
subnet_id=ocid1.subnet.oc1.phx.aaaaaaaaq7tlicq4csabg3hmfjmv3szst53xnhtm2nv6l6m7ma5gh5im7glq
image=Oracle-Linux-7.5-2018.10.16-0
ad=1
gluster_server_shape=VM.Standard2.4
blksize_tb=1
blk_num=2
compartment_id=ocid1.compartment.oc1..aaaaaaaathxc5bc6bv5qgqrzpc2ggnv2lrpcgsvbjpgugoiylw64s3qi6yia
PRE=`uuidgen | cut -c-5`
#region=us-ashburn-1
#region=eu-frankfurt-1
region=us-phoenix-1
#region=uk-london-1

AD=`oci iam availability-domain list -c $compartment_id --region $region --output table | grep 'AD-'$ad | awk '{ print $4 }'`
OS=`oci compute image list -c $compartment_id --region $region --output table --query "data [*].{ImageName:\"display-name\", OCID:id}" | grep $image | awk '{ print $4 }'`
INFO='--region '$region' --availability-domain '$AD' -c '$compartment_id
subnet=`echo $full_CIDR | awk -F. '{print $1"."$2"."$3}'`

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color